"""add financial check constraints

Revision ID: dba5f13a525e
Revises: 325f3e3f28b0
Create Date: 2026-08-30 17:50:22.181316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba5f13a525e'
down_revision: Union[str, Sequence[str], None] = '325f3e3f28b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_drink_session_packets_positive', 'drink_sessions', 'packets_used > 0')
    op.create_check_constraint('ck_drink_session_price_positive', 'drink_sessions', 'price_per_packet > 0')
    op.create_check_constraint('ck_drink_session_total_nonnegative', 'drink_sessions', 'total_cost >= 0')
    op.create_check_constraint('ck_payment_amount_positive', 'payments', 'amount > 0')
    op.create_check_constraint('ck_session_participant_amount_nonnegative', 'session_participants', 'amount_owed >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_session_participant_amount_nonnegative', 'session_participants', type_='check')
    op.drop_constraint('ck_payment_amount_positive', 'payments', type_='check')
    op.drop_constraint('ck_drink_session_total_nonnegative', 'drink_sessions', type_='check')
    op.drop_constraint('ck_drink_session_price_positive', 'drink_sessions', type_='check')
    op.drop_constraint('ck_drink_session_packets_positive', 'drink_sessions', type_='check')
    # ### end Alembic commands ###
