"""add password reset requests

Revision ID: f457caf69440
Revises: dba5f13a525e
Create Date: 2026-08-31 18:13:47.214042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f457caf69440'
down_revision: Union[str, Sequence[str], None] = 'dba5f13a525e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_requests_expires_at'), 'password_reset_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_requests_used'), 'password_reset_requests', ['used'], unique=False)
    op.create_index(op.f('ix_password_reset_requests_user_id'), 'password_reset_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_requests_user_id'), table_name='password_reset_requests')
    op.drop_index(op.f('ix_password_reset_requests_used'), table_name='password_reset_requests')
    op.drop_index(op.f('ix_password_reset_requests_expires_at'), table_name='password_reset_requests')
    op.drop_table('password_reset_requests')
    # ### end Alembic commands ###
